### ISSUE TITLE
Auto-close tags in erb files

### ISSUE THREAD

**Issue by rwehresmann** [formulahendry/vscode-auto-close-tag#65]
Currently, I could not find a way to make that work with `html.erb` files (commonly used in Ruby on Rails). Any clue of how can I do that?

**Comment by formulahendry** [comment]
Go to `File`->`Preference`->`Settings`, and add below settings, also add `ruby` in the `activationOnLanguage` list
```json
"auto-close-tag.activationOnLanguage": [
        "xml",
        "php",
        "blade",
        "ejs",
        "jinja",
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "plaintext",
        "markdown",
        "vue",
        "liquid",
        "ruby"
]
```

**Comment by rwehresmann** [comment]
Thanks for the kick response, but still not working. Here are my custom settings:

```
{
    "window.zoomLevel": -1,
    "terminal.integrated.shell.linux": "bash",
    "terminal.integrated.shellArgs.linux": [ "-l" ],
    "ruby.lint": {
        "reek": true,
        "rubocop": true,
        "ruby": true,
        "fasterer": true,
        "debride": true,
        "ruby-lint": true
    },
    "sync.lastUpload": "2017-10-22T01:13:14.510Z",
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastDownload": "",
    "sync.forceDownload": false,
    "sync.anonymousGist": false,
    "sync.host": "",
    "sync.pathPrefix": "",
    "sync.quietSync": false,
    "sync.askGistName": false,
    "workbench.colorTheme": "Monokai",
    "auto-close-tag.activationOnLanguage": [
        "xml",
        "php",
        "blade",
        "ejs",
        "jinja",
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "plaintext",
        "markdown",
        "vue",
        "liquid",
        "ruby"
    ]
}
```

**Comment by formulahendry** [comment]
Hi @rwehresmann , do you install any extension for Ruby on Rails? Could you check in VS Code to see whether it is showing `Ruby` or other?

![image](https://user-images.githubusercontent.com/1050213/31859102-3c573b0c-b739-11e7-8984-cd17d8de319c.png)

**Comment by formulahendry** [comment]
I guess you have installed the https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby. In that case, you need to add `erb` instead of `ruby` to the `auto-close-tag.activationOnLanguage`

**Comment by formulahendry** [comment]
Hi @rwehresmann , I have published a new version to support erb file into the default `auto-close-tag.activationOnLanguage` setting, please install and have a try. So you could just remove the `auto-close-tag.activationOnLanguage` setting to let the default setting take effect.

**Comment by rwehresmann** [comment]
You'rre right @formulahendry , I installed this Ruby plugin. The language showing is `erb` in this case.

I reinstalled the plugin, but still not working (always need to use the shortcut `alt + .` to close the tag).

**Comment by formulahendry** [comment]
Have you deleted the auto-close-tag.activationOnLanguage setting?

**Comment by rwehresmann** [comment]
Yes. Now I realized something: when I open a tag, vscode imediatly closes it (i.e., typing `<` automatically results in `<>`). That is the problem. If I deletes that ant type `<div` for instance, when I close the tag by myself (`<div>`), auto-close-tag works, closing the div (`<div></div>`). 

 I just need to figure out how to disable this behavior and everithing should work perfectly (:

**Comment by formulahendry** [comment]
> typing `<` automatically results in `<>`

Ruby extension does that, you could use below setting to disable this behavior:
```json
"editor.autoClosingBrackets": false
```

Either, there is another way to auto close tag, type `<div></` results in `<div></div>`, use below setting to enable this:
```json
"auto-close-tag.fullMode": true
```

**Comment by swedishpotato** [comment]
I have tried every combination of the above solutions here but .erb files simply do not get picked up and processed as .html files would do. A pity - because in essence all of my .html have the .erb extension too.

**Comment by camilova** [comment]
For me, I get it work putting `html.erb` on activation languages.

```
"auto-close-tag.activationOnLanguage": [
        "xml",
        "php",
        "blade",
        "ejs",
        "jinja",
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "plaintext",
        "markdown",
        "vue",
        "liquid",
        "ruby",
        "html.erb"
]
```
